ustawienia:
  numerIndeksu: 461009
  wycena: "CENY_BEZ_ZMIAN"
  zamowienia: "GRUPOWE"
  zaopatrzenie: "POJEDYNCZE"
  wydarzenia: "RAPORT_SPRZEDAŻY"
  liczbaZadan: 200
  redisHost: "192.168.50.178"
  redisPort: 8989
  activeRedis: false
